version: '4.0'

services:
  db:
    image: postgres:14.7-alpine
    container_name: relex_farm_db
    environment:
      POSTGRES_DB: relex_farm
      POSTGRES_USER: tunebaker
      POSTGRES_PASSWORD: 12
    ports:
      - "54321:5432"
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    restart: unless-stopped