server:
  port: 8082
jwt:
  secret: ebon990erb098bre0
  lifetime: 72h
spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/relex_farm
    username: tunebaker
    password: 12
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: data
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    default-schema: public

